apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: place-bots
resources:
- namespace.yaml
- deployment.yaml
- configmap.yaml
- imagesecret.yaml
configMapGenerator:
  - behavior: replace
    name: config-json
    namespace: place-bots
    files:
      - config.json